# Configure true colors
set -g default-terminal "screen-256color"

# Bind prefix to "ctrl-b"
set -g prefix C-b
unbind C-a
bind-key C-b send-prefix

# Bind pane-spltting to
# Vertical "|"
# Horizontal "-"
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Enable the mouse in tmux
set -g mouse on

# Pane navigation
bind -r h select-pane -L
bind -r k select-pane -U
bind -r l select-pane -R
bind -r j select-pane -D

# Support easy pane-resizing (repeat-time set to 5)
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -U 5
bind-key -r L resize-pane -R 5
bind-key -r K resize-pane -D 5

# Min-max zooming for the active pane
bind-key -r m resize-pane -Z

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# ++ Plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'
# set -g @plugin 'tmux-plugins/tmux-resurrect'  # Persist for pc restart
# set -g @plugin 'tmux-plugins/tmux-continuum'  # Auto-save sess per 15 min

set -g @tmux_power_theme 'sky'
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Refresh tmux config
unbind r
bind r source-file ~/.tmux.conf

# Init tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
